"""Helpers for creating ready-to-run game states."""

from __future__ import annotations

import random

from .models import Card, CardType, GameState, ManaColor, PlayerState


def create_starting_game_state() -> GameState:
    """Create a randomized game state suitable for first end-to-end integration."""
    p1_deck = [
        "p1_c1",
        "p1_c2",
        "p1_c3",
        "p1_c4",
        "p1_c5",
        "p1_c6",
        "p1_c7",
        "p1_c8",
        "p1_c9",
        "p1_c10",
        "p1_c11",
        "p1_c12",
        "p1_c13",
        "p1_c14",
        "p1_l1",
        "p1_l2",
        "p1_l3",
        "p1_l4",
        "p1_l5",
        "p1_l6",
        "p1_l7",
        "p1_l8",
        "p1_l9",
        "p1_l10",
    ]
    p2_deck = [
        "p2_c1",
        "p2_c2",
        "p2_c3",
        "p2_c4",
        "p2_c5",
        "p2_c6",
        "p2_c7",
        "p2_c8",
        "p2_c9",
        "p2_c10",
        "p2_c11",
        "p2_c12",
        "p2_c13",
        "p2_c14",
        "p2_l1",
        "p2_l2",
        "p2_l3",
        "p2_l4",
        "p2_l5",
        "p2_l6",
        "p2_l7",
        "p2_l8",
        "p2_l9",
        "p2_l10",
    ]

    random.shuffle(p1_deck)
    random.shuffle(p2_deck)

    p1 = PlayerState(
        id="p1",
        library=p1_deck[5:],
        hand=p1_deck[:5],
    )
    p2 = PlayerState(
        id="p2",
        library=p2_deck[5:],
        hand=p2_deck[:5],
    )

    cards = {
        "p1_c1": Card(
            id="p1_c1",
            name="Frontier Wolf",
            owner_id="p1",
            mana_cost="1G",
            card_type=CardType.CREATURE,
            power=2,
            toughness=2,
        ),
        "p1_c2": Card(
            id="p1_c2",
            name="Canopy Stalker",
            owner_id="p1",
            mana_cost="2G",
            card_type=CardType.CREATURE,
            power=2,
            toughness=3,
        ),
        "p1_c3": Card(
            id="p1_c3",
            name="Sunspire Adept",
            owner_id="p1",
            mana_cost="1W",
            card_type=CardType.CREATURE,
            power=2,
            toughness=1,
        ),
        "p1_c4": Card(
            id="p1_c4",
            name="Dawn Sentry",
            owner_id="p1",
            mana_cost="2W",
            card_type=CardType.CREATURE,
            power=2,
            toughness=3,
        ),
        "p1_c5": Card(
            id="p1_c5",
            name="Bramble Charger",
            owner_id="p1",
            mana_cost="2G",
            card_type=CardType.CREATURE,
            power=3,
            toughness=2,
        ),
        "p1_c6": Card(
            id="p1_c6",
            name="Meadow Guardian",
            owner_id="p1",
            mana_cost="3W",
            card_type=CardType.CREATURE,
            power=4,
            toughness=3,
        ),
        "p1_c7": Card(
            id="p1_c7",
            name="Loxodon Warden",
            owner_id="p1",
            mana_cost="3W",
            card_type=CardType.CREATURE,
            power=3,
            toughness=3,
        ),
        "p1_c8": Card(
            id="p1_c8",
            name="Ancient Grove Behemoth",
            owner_id="p1",
            mana_cost="4GW",
            card_type=CardType.CREATURE,
            power=6,
            toughness=6,
        ),
        "p1_c9": Card(
            id="p1_c9",
            name="Sunfield Outrider",
            owner_id="p1",
            mana_cost="1W",
            card_type=CardType.CREATURE,
            power=1,
            toughness=3,
        ),
        "p1_c10": Card(
            id="p1_c10",
            name="Mossglade Scout",
            owner_id="p1",
            mana_cost="1G",
            card_type=CardType.CREATURE,
            power=2,
            toughness=2,
        ),
        "p1_c11": Card(
            id="p1_c11",
            name="Verdant Shieldmate",
            owner_id="p1",
            mana_cost="2G",
            card_type=CardType.CREATURE,
            power=3,
            toughness=3,
        ),
        "p1_c12": Card(
            id="p1_c12",
            name="Skychapel Healer",
            owner_id="p1",
            mana_cost="2W",
            card_type=CardType.CREATURE,
            power=2,
            toughness=4,
        ),
        "p1_c13": Card(
            id="p1_c13",
            name="Verdict of Thorns",
            owner_id="p1",
            mana_cost="2W",
            card_type=CardType.SORCERY,
            effect_kind="destroy_target_creature",
            oracle_text="Destroy target creature.",
        ),
        "p1_c14": Card(
            id="p1_c14",
            name="Trailfire Bolt",
            owner_id="p1",
            mana_cost="1R",
            card_type=CardType.SORCERY,
            effect_kind="damage_target_creature",
            effect_value=2,
            oracle_text="Trailfire Bolt deals 2 damage to target creature.",
        ),
        "p1_l1": Card(
            id="p1_l1",
            name="Forest",
            owner_id="p1",
            mana_cost="",
            card_type=CardType.LAND,
            produces_mana=(ManaColor.GREEN,),
        ),
        "p1_l2": Card(
            id="p1_l2",
            name="Forest",
            owner_id="p1",
            mana_cost="",
            card_type=CardType.LAND,
            produces_mana=(ManaColor.GREEN,),
        ),
        "p1_l3": Card(
            id="p1_l3",
            name="Forest",
            owner_id="p1",
            mana_cost="",
            card_type=CardType.LAND,
            produces_mana=(ManaColor.GREEN,),
        ),
        "p1_l4": Card(
            id="p1_l4",
            name="Plains",
            owner_id="p1",
            mana_cost="",
            card_type=CardType.LAND,
            produces_mana=(ManaColor.WHITE,),
        ),
        "p1_l5": Card(
            id="p1_l5",
            name="Plains",
            owner_id="p1",
            mana_cost="",
            card_type=CardType.LAND,
            produces_mana=(ManaColor.WHITE,),
        ),
        "p1_l6": Card(
            id="p1_l6",
            name="Forest",
            owner_id="p1",
            mana_cost="",
            card_type=CardType.LAND,
            produces_mana=(ManaColor.GREEN,),
        ),
        "p1_l7": Card(
            id="p1_l7",
            name="Forest",
            owner_id="p1",
            mana_cost="",
            card_type=CardType.LAND,
            produces_mana=(ManaColor.GREEN,),
        ),
        "p1_l8": Card(
            id="p1_l8",
            name="Plains",
            owner_id="p1",
            mana_cost="",
            card_type=CardType.LAND,
            produces_mana=(ManaColor.WHITE,),
        ),
        "p1_l9": Card(
            id="p1_l9",
            name="Mountain",
            owner_id="p1",
            mana_cost="",
            card_type=CardType.LAND,
            produces_mana=(ManaColor.RED,),
        ),
        "p1_l10": Card(
            id="p1_l10",
            name="Mountain",
            owner_id="p1",
            mana_cost="",
            card_type=CardType.LAND,
            produces_mana=(ManaColor.RED,),
        ),
        "p2_c1": Card(
            id="p2_c1",
            name="Night Drake",
            owner_id="p2",
            mana_cost="2B",
            card_type=CardType.CREATURE,
            power=2,
            toughness=3,
        ),
        "p2_c2": Card(
            id="p2_c2",
            name="Stoneguard",
            owner_id="p2",
            mana_cost="3U",
            card_type=CardType.CREATURE,
            power=2,
            toughness=4,
        ),
        "p2_c3": Card(
            id="p2_c3",
            name="Bog Lurker",
            owner_id="p2",
            mana_cost="1B",
            card_type=CardType.CREATURE,
            power=2,
            toughness=2,
        ),
        "p2_c4": Card(
            id="p2_c4",
            name="Mistcloak Adept",
            owner_id="p2",
            mana_cost="2U",
            card_type=CardType.CREATURE,
            power=3,
            toughness=2,
        ),
        "p2_c5": Card(
            id="p2_c5",
            name="Tidechannel Oracle",
            owner_id="p2",
            mana_cost="3U",
            card_type=CardType.CREATURE,
            power=2,
            toughness=4,
        ),
        "p2_c6": Card(
            id="p2_c6",
            name="Sunken Veteran",
            owner_id="p2",
            mana_cost="2B",
            card_type=CardType.CREATURE,
            power=3,
            toughness=3,
        ),
        "p2_c7": Card(
            id="p2_c7",
            name="Graveborn Marauder",
            owner_id="p2",
            mana_cost="4B",
            card_type=CardType.CREATURE,
            power=4,
            toughness=4,
        ),
        "p2_c8": Card(
            id="p2_c8",
            name="Abyssal Colossus",
            owner_id="p2",
            mana_cost="4UB",
            card_type=CardType.CREATURE,
            power=6,
            toughness=6,
        ),
        "p2_c9": Card(
            id="p2_c9",
            name="Fathom Initiate",
            owner_id="p2",
            mana_cost="1U",
            card_type=CardType.CREATURE,
            power=1,
            toughness=3,
        ),
        "p2_c10": Card(
            id="p2_c10",
            name="Gravetide Cutthroat",
            owner_id="p2",
            mana_cost="1B",
            card_type=CardType.CREATURE,
            power=2,
            toughness=1,
        ),
        "p2_c11": Card(
            id="p2_c11",
            name="Mistvault Scholar",
            owner_id="p2",
            mana_cost="2U",
            card_type=CardType.CREATURE,
            power=2,
            toughness=3,
        ),
        "p2_c12": Card(
            id="p2_c12",
            name="Duskfen Ambusher",
            owner_id="p2",
            mana_cost="2B",
            card_type=CardType.CREATURE,
            power=3,
            toughness=2,
        ),
        "p2_c13": Card(
            id="p2_c13",
            name="Abyssal Verdict",
            owner_id="p2",
            mana_cost="2B",
            card_type=CardType.SORCERY,
            effect_kind="destroy_target_creature",
            oracle_text="Destroy target creature.",
        ),
        "p2_c14": Card(
            id="p2_c14",
            name="Shadowflame Lash",
            owner_id="p2",
            mana_cost="1R",
            card_type=CardType.SORCERY,
            effect_kind="damage_target_creature",
            effect_value=2,
            oracle_text="Shadowflame Lash deals 2 damage to target creature.",
        ),
        "p2_l1": Card(
            id="p2_l1",
            name="Swamp",
            owner_id="p2",
            mana_cost="",
            card_type=CardType.LAND,
            produces_mana=(ManaColor.BLACK,),
        ),
        "p2_l2": Card(
            id="p2_l2",
            name="Island",
            owner_id="p2",
            mana_cost="",
            card_type=CardType.LAND,
            produces_mana=(ManaColor.BLUE,),
        ),
        "p2_l3": Card(
            id="p2_l3",
            name="Island",
            owner_id="p2",
            mana_cost="",
            card_type=CardType.LAND,
            produces_mana=(ManaColor.BLUE,),
        ),
        "p2_l4": Card(
            id="p2_l4",
            name="Swamp",
            owner_id="p2",
            mana_cost="",
            card_type=CardType.LAND,
            produces_mana=(ManaColor.BLACK,),
        ),
        "p2_l5": Card(
            id="p2_l5",
            name="Swamp",
            owner_id="p2",
            mana_cost="",
            card_type=CardType.LAND,
            produces_mana=(ManaColor.BLACK,),
        ),
        "p2_l6": Card(
            id="p2_l6",
            name="Island",
            owner_id="p2",
            mana_cost="",
            card_type=CardType.LAND,
            produces_mana=(ManaColor.BLUE,),
        ),
        "p2_l7": Card(
            id="p2_l7",
            name="Island",
            owner_id="p2",
            mana_cost="",
            card_type=CardType.LAND,
            produces_mana=(ManaColor.BLUE,),
        ),
        "p2_l8": Card(
            id="p2_l8",
            name="Swamp",
            owner_id="p2",
            mana_cost="",
            card_type=CardType.LAND,
            produces_mana=(ManaColor.BLACK,),
        ),
        "p2_l9": Card(
            id="p2_l9",
            name="Mountain",
            owner_id="p2",
            mana_cost="",
            card_type=CardType.LAND,
            produces_mana=(ManaColor.RED,),
        ),
        "p2_l10": Card(
            id="p2_l10",
            name="Mountain",
            owner_id="p2",
            mana_cost="",
            card_type=CardType.LAND,
            produces_mana=(ManaColor.RED,),
        ),
    }

    state = GameState(
        players={"p1": p1, "p2": p2},
        cards=cards,
        active_player_id="p1",
        priority_player_id="p1",
    )
    state.event_log.append("Game initialized with shuffled starting libraries and 5-card hands")
    return state
