"""Helpers for creating ready-to-run game states."""

from __future__ import annotations

from .models import Card, CardType, GameState, ManaColor, PlayerState


def create_starting_game_state() -> GameState:
    """Create a static game state suitable for first end-to-end integration."""
    p1 = PlayerState(
        id="p1",
        library=[
            "p1_c1",
            "p1_c2",
            "p1_c3",
            "p1_c4",
            "p1_c5",
            "p1_c6",
            "p1_l1",
            "p1_l2",
            "p1_l3",
            "p1_l4",
        ],
        hand=["p1_c7", "p1_c8", "p1_l5"],
    )
    p2 = PlayerState(
        id="p2",
        library=[
            "p2_c1",
            "p2_c2",
            "p2_c3",
            "p2_c4",
            "p2_c5",
            "p2_c6",
            "p2_l1",
            "p2_l2",
            "p2_l3",
            "p2_l4",
        ],
        hand=["p2_c7", "p2_c8", "p2_l5"],
    )

    cards = {
        "p1_c1": Card(
            id="p1_c1",
            name="Frontier Wolf",
            owner_id="p1",
            mana_cost="1G",
            card_type=CardType.CREATURE,
            power=2,
            toughness=2,
        ),
        "p1_c2": Card(
            id="p1_c2",
            name="Canopy Stalker",
            owner_id="p1",
            mana_cost="2G",
            card_type=CardType.CREATURE,
            power=2,
            toughness=3,
        ),
        "p1_c3": Card(
            id="p1_c3",
            name="Sunspire Adept",
            owner_id="p1",
            mana_cost="1W",
            card_type=CardType.CREATURE,
            power=2,
            toughness=1,
        ),
        "p1_c4": Card(
            id="p1_c4",
            name="Dawn Sentry",
            owner_id="p1",
            mana_cost="2W",
            card_type=CardType.CREATURE,
            power=2,
            toughness=3,
        ),
        "p1_c5": Card(
            id="p1_c5",
            name="Bramble Charger",
            owner_id="p1",
            mana_cost="2G",
            card_type=CardType.CREATURE,
            power=3,
            toughness=2,
        ),
        "p1_c6": Card(
            id="p1_c6",
            name="Meadow Guardian",
            owner_id="p1",
            mana_cost="3W",
            card_type=CardType.CREATURE,
            power=4,
            toughness=3,
        ),
        "p1_c7": Card(
            id="p1_c7",
            name="Loxodon Warden",
            owner_id="p1",
            mana_cost="3W",
            card_type=CardType.CREATURE,
            power=3,
            toughness=3,
        ),
        "p1_c8": Card(
            id="p1_c8",
            name="Ancient Grove Behemoth",
            owner_id="p1",
            mana_cost="4GW",
            card_type=CardType.CREATURE,
            power=6,
            toughness=6,
        ),
        "p1_l1": Card(
            id="p1_l1",
            name="Forest",
            owner_id="p1",
            mana_cost="",
            card_type=CardType.LAND,
            produces_mana=(ManaColor.GREEN,),
        ),
        "p1_l2": Card(
            id="p1_l2",
            name="Forest",
            owner_id="p1",
            mana_cost="",
            card_type=CardType.LAND,
            produces_mana=(ManaColor.GREEN,),
        ),
        "p1_l3": Card(
            id="p1_l3",
            name="Forest",
            owner_id="p1",
            mana_cost="",
            card_type=CardType.LAND,
            produces_mana=(ManaColor.GREEN,),
        ),
        "p1_l4": Card(
            id="p1_l4",
            name="Plains",
            owner_id="p1",
            mana_cost="",
            card_type=CardType.LAND,
            produces_mana=(ManaColor.WHITE,),
        ),
        "p1_l5": Card(
            id="p1_l5",
            name="Plains",
            owner_id="p1",
            mana_cost="",
            card_type=CardType.LAND,
            produces_mana=(ManaColor.WHITE,),
        ),
        "p2_c1": Card(
            id="p2_c1",
            name="Night Drake",
            owner_id="p2",
            mana_cost="2B",
            card_type=CardType.CREATURE,
            power=2,
            toughness=3,
        ),
        "p2_c2": Card(
            id="p2_c2",
            name="Stoneguard",
            owner_id="p2",
            mana_cost="3U",
            card_type=CardType.CREATURE,
            power=2,
            toughness=4,
        ),
        "p2_c3": Card(
            id="p2_c3",
            name="Bog Lurker",
            owner_id="p2",
            mana_cost="1B",
            card_type=CardType.CREATURE,
            power=2,
            toughness=2,
        ),
        "p2_c4": Card(
            id="p2_c4",
            name="Mistcloak Adept",
            owner_id="p2",
            mana_cost="2U",
            card_type=CardType.CREATURE,
            power=3,
            toughness=2,
        ),
        "p2_c5": Card(
            id="p2_c5",
            name="Tidechannel Oracle",
            owner_id="p2",
            mana_cost="3U",
            card_type=CardType.CREATURE,
            power=2,
            toughness=4,
        ),
        "p2_c6": Card(
            id="p2_c6",
            name="Sunken Veteran",
            owner_id="p2",
            mana_cost="2B",
            card_type=CardType.CREATURE,
            power=3,
            toughness=3,
        ),
        "p2_c7": Card(
            id="p2_c7",
            name="Graveborn Marauder",
            owner_id="p2",
            mana_cost="4B",
            card_type=CardType.CREATURE,
            power=4,
            toughness=4,
        ),
        "p2_c8": Card(
            id="p2_c8",
            name="Abyssal Colossus",
            owner_id="p2",
            mana_cost="4UB",
            card_type=CardType.CREATURE,
            power=6,
            toughness=6,
        ),
        "p2_l1": Card(
            id="p2_l1",
            name="Swamp",
            owner_id="p2",
            mana_cost="",
            card_type=CardType.LAND,
            produces_mana=(ManaColor.BLACK,),
        ),
        "p2_l2": Card(
            id="p2_l2",
            name="Island",
            owner_id="p2",
            mana_cost="",
            card_type=CardType.LAND,
            produces_mana=(ManaColor.BLUE,),
        ),
        "p2_l3": Card(
            id="p2_l3",
            name="Island",
            owner_id="p2",
            mana_cost="",
            card_type=CardType.LAND,
            produces_mana=(ManaColor.BLUE,),
        ),
        "p2_l4": Card(
            id="p2_l4",
            name="Swamp",
            owner_id="p2",
            mana_cost="",
            card_type=CardType.LAND,
            produces_mana=(ManaColor.BLACK,),
        ),
        "p2_l5": Card(
            id="p2_l5",
            name="Swamp",
            owner_id="p2",
            mana_cost="",
            card_type=CardType.LAND,
            produces_mana=(ManaColor.BLACK,),
        ),
    }

    state = GameState(
        players={"p1": p1, "p2": p2},
        cards=cards,
        active_player_id="p1",
        priority_player_id="p1",
    )
    state.event_log.append("Game initialized with static starting state")
    return state
